apiVersion: nmstate.io/v1
kind: NodeNetworkConfigurationPolicy
metadata:
  name: master0-bond1-policy
spec:
  nodeSelector:
    kubernetes.io/hostname: master0
  desiredState:     
    interfaces:
    - name: ens2f0
      description: Ethernet ens2f0
      type: ethernet
      state: up
      ipv4:
        enabled: false
      mtu: 1500
    - name: ens5f2
      description: Ethernet ens5f2
      type: ethernet
      state: up
      ipv4:
        enabled: false
      mtu: 1500
    - name: bond1
      description: Bond with ports ens2f0 and ens5f2
      type: bond
      state: up
      ipv4:
        enabled: false
      link-aggregation:
        mode: 802.3ad
        options:
          miimon: '100'
        port:
        - ens2f0
        - ens5f2
      mtu: 1500
    - name: bond1.3400
      description: vlan 3400 using bond1
      type: vlan
      state: up
      vlan:
        base-iface: bond1
        id: 3400
      mtu: 1500
    - name: bond1.3401
      description: vlan 3401 using bond1
      type: vlan
      state: up
      vlan:
        base-iface: bond1
        id: 3401
      mtu: 1500
    - name: br3400
      description: Linux bridge with bond1.3400 as a port
      type: linux-bridge
      state: up
      ipv4:
        dhcp: false
        address:
        - ip: Y.Y.Y.Y
          prefix-length: 24
        enabled: true                          
      bridge:
        options:
          stp:
            enabled: false
        port:
          - name: bond1.3400
    - name: br3401
      description: Linux bridge with bond1.3401 as a port
      type: linux-bridge
      state: up
      ipv4:
        dhcp: false
        address:
        - ip: X.X.X.X
          prefix-length: 24
        enabled: true                          
      bridge:
        options:
          stp:
            enabled: false
        port:
          - name: bond1.3401
