# https://infohub.delltechnologies.com/en-US/l/red-hat-openshift-4-12-deployment-on-dell-powerflex-4-5/openshift-ingress-api-network-configuration-2/1/
interfaces:
- name: ens2f0
  description: Ethernet ens2f0
  type: ethernet
  state: up
  ipv4:
    enabled: false
  mtu: 1500
- name: ens3f0
  description: Ethernet ens3f0
  type: ethernet
  state: up
  ipv4:
    enabled: false
  mtu: 1500
- name: bond0
  description: Bond with ports ens2f0 and ens3f0
  type: bond
  state: up
  ipv4:
    enabled: false
  link-aggregation:
    mode: 802.3ad
    options:
      miimon: '100'
    port:
    - ens2f0
    - ens3f0
  mtu: 1500
- name: bond0.105
  description: vlan 205 using bond0
  type: vlan
  state: up
  ipv4:
    address:
    - ip: 172.16.105.192  
      prefix-length: 24
    enabled: true
  vlan:
    base-iface: bond0
    id: 205
  mtu: 1500
routes:
  config:
  - destination: 0.0.0.0/0
    next-hop-address: 172.16.105.10
    next-hop-interface: bond0.105
dns-resolver:
  config:
    search:
    - ocp412.com
    server:
    - 172.16.105.191
    - 100.80.112.1
